server:
  port: 8080
spring:
  profiles:
    active: dev
  application:
    name: demo
  datasource:
    url: jdbc:mysql://192.168.110.131:3306/hmall?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&serverTimezone=Asia/Shanghai
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123
